//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semana_5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Personas> Personas { get; set; }
    
        public virtual ObjectResult<ppInsertPersona_Result> ppInsertPersona(string nombes, string apellidos, string telefono, string orientación_Sexual, string estado_Civil, Nullable<System.DateTime> fecha_Inscripcion)
        {
            var nombesParameter = nombes != null ?
                new ObjectParameter("Nombes", nombes) :
                new ObjectParameter("Nombes", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var orientación_SexualParameter = orientación_Sexual != null ?
                new ObjectParameter("Orientación_Sexual", orientación_Sexual) :
                new ObjectParameter("Orientación_Sexual", typeof(string));
    
            var estado_CivilParameter = estado_Civil != null ?
                new ObjectParameter("Estado_Civil", estado_Civil) :
                new ObjectParameter("Estado_Civil", typeof(string));
    
            var fecha_InscripcionParameter = fecha_Inscripcion.HasValue ?
                new ObjectParameter("Fecha_Inscripcion", fecha_Inscripcion) :
                new ObjectParameter("Fecha_Inscripcion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ppInsertPersona_Result>("ppInsertPersona", nombesParameter, apellidosParameter, telefonoParameter, orientación_SexualParameter, estado_CivilParameter, fecha_InscripcionParameter);
        }
    }
}
