//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semana_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public int Id { get; set; }
        public string Nombes { get; set; }
        public string Apellidos { get; set; }
        public string Telefono { get; set; }
        public string Orientación_Sexual { get; set; }
        public string Estado_Civil { get; set; }
        public System.DateTime Fecha_Inscripcion { get; set; }
    }
}
